name: Code Security Scan

on:
  push:
    branches:
      - main
      - bug-fixing
  pull_request:
  schedule:
    - cron: '0 0 * * 0'  # Optional: run weekly

jobs:
  codeql:
    name: CodeQL Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python
          # You can add custom queries or override search paths if needed

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:python"

  bandit:
    name: Bandit Security Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -r .
