name: ssdk_rsrc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  dio: ^5.1.0
  url_launcher: ^6.1.6
  http: ^1.0.0
  flutter_html: ^3.0.0-beta.2
  app_links: ^6.3.3
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
